GET http://localhost:7000/products

###
POST http://localhost:7000/auth/register
Content-Type: application/json

{
  "email": "daniel@abc.com",
  "firstName": "Daniel",
  "lastName": "Huong",
  "password": "aaaaaa"
}